name: Build and Push Container

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push container
        run: |
          podman build . -t path_to_adventure:latest
          podman login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io
          podman push quay.io/jbaldus/path_to_adventure:latest
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

