name: Build and Push Container

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

env:
  QUAY_USERNAME: jbaldus
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: path_to_adventure
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: Push container
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags:  ${{ steps.build-image.outputs.tags }}
          registry: quay.io/${{ env.QUAY_USERNAME }}
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_PASSWORD }}

